#Стадии
stages:
  - build
  - test
  - deploy_preprod
  - deploy_prod

#Переменные
variables:
  PROD_LOGIN: "production_login"
  PREPROD_LOGIN: "preprod_login"  
  CI_DEBUG_TRACE: "true" #Подробное логирование

#Подлючение внешних шаблонов  
include:  
  project: bev0802/templates  # Указывайть путь к проекту без https://gitlab.com/
  file: /smoke-test.gitlab_ci.yml
  ref: main  

build-job:  
  stage: build  
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - echo "No lint issues found."

deploy-to-preprod:
  stage: deploy_preprod
  environment: preprod
  variables:
    MyLogin: "preprod_login"
  script:
    - echo "Deploying to pre-production environment..."
    - echo "Login with $MyLogin"

deploy-to-production:
  stage: deploy_prod
  environment: production
  variables:
    MyLogin: "production_login"
  script:
    - echo "Deploying to production environment..."
    - echo "Login with $MyLogin"

pages:
  stage: deploy_prod
  script:
    - echo 'dream house'
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - public
  only:
    - main

stop_previous_pipelines:
  stage: build
  script:
    - > 
      curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" 
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel"
  only:
    - main
